### ISSUE TITLE
"Start node not set"

### ISSUE THREAD

**Issue by LiMengyang990726** [hliejun/hypedyn-the-patrol#1]
Hi, I followed the instruction given in "hypedyn-tutorial-1", until page 9
![screen shot 2019-01-27 at 2 44 14 pm](https://user-images.githubusercontent.com/34411863/51797636-09da5400-2242-11e9-80a8-a4b9fa9dd055.png)

After successfully setting this, when I click run, I got the error page:
![screen shot 2019-01-27 at 2 43 21 pm](https://user-images.githubusercontent.com/34411863/51797640-1d85ba80-2242-11e9-8159-c00b9b24f279.png)

Could anyone help me to solve this?

**Comment by hliejun** [comment]
@LiMengyang990726 Hi Mengyang! 

Perhaps you can see if you have designated the node that you intend to start with as the start node **by checking the "Start node" checkbox at the top right corner of the node view**. I am referring to the checkbox "B" in this image: 

https://github.com/narrativeandplay/hypedyn2/blob/development/doc/images/hypedyn-tutorial-1-figure-5.png

Also for future questions, you can try filing an issue at the actual HypeDyn repo so that you can get responses from the developers of HypeDyn directly: 

https://github.com/narrativeandplay/hypedyn2 

If you're enrolled in a New Media module at NUS that uses HypeDyn, you can also try asking your tutors, lecturers and friends on IVLE forums. Of course, you can also ask me questions here! However, I am not a HypeDyn developer so I might not be able to answer all of them correctly. I'll try my best to =)

Cheers!

**Comment by LiMengyang990726** [comment]
Thank you! That works!
